# Generated by Django 5.2.7 on 2025-10-20 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lector',
            new_name='Lecturer',
        ),
    ]
