# Generated by Django 5.2.7 on 2025-11-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='launch_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='spacecraft',
            name='launch_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
