# Generated by Django 5.2.7 on 2025-10-17 18:10
import random

from django.db import migrations

def add_barcodes(apps, schema_editor):
    Products = apps.get_model('main_app', 'Product')
    all_products = Products.objects.all()
    all_barcodes = random.sample(
        range(100000000, 1000000000),
        len(all_products))

    for i in range(len(all_products)):
        product = all_products[i]
        product.barcode = all_barcodes[i]
        product.save()

def reverse_barcodes(apps, schema_editor):
    Products = apps.get_model('main_app', 'Product')
    for product in Products.objects.all():
        product.barcode = 0
        product.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_product_count'),
    ]

    operations = [
        migrations.RunPython(add_barcodes,reverse_code= reverse_barcodes),
    ]
