# Generated by Django 5.2.7 on 2025-11-05 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='director',
            old_name='year_of_experience',
            new_name='years_of_experience',
        ),
    ]
