# Generated by Django 5.2.7 on 2025-10-17 17:42

from django.db import migrations

MULTIPLIER = 120
def set_price(apps, schema_editor):
    SmartphoneModel =apps.get_model('main_app', 'Smartphone')
    #todo f object
    for phone in SmartphoneModel.objects.all():
        phone.price = len(phone.brand) * MULTIPLIER
        phone.save()

def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    for phone in SmartphoneModel.objects.all():
        phone.category = 'Cheap' if phone.price < 750 else "Expensive"
        phone.save()

def set_category_and_price(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)

def reset_category(apps, schema_editor):
    SmartphoneModel = apps.get('main_app', 'Smartphone')
    default_category =  SmartphoneModel._meta.get_field('category').default

    for phone in SmartphoneModel.objects.all():
        phone.category = default_category
        phone.save()
def reset_price(apps, schema_editor):
    SmartphoneModel = apps.get('main_app', 'Smartphone')
    default_price = SmartphoneModel._meta.get_field('price').default

    for phone in SmartphoneModel.objects.all():
        phone.price = default_price
        phone.save()


def reset_category_and_price(apps, schema_editor):
    reset_category(apps, schema_editor)
    reset_price(apps, schema_editor)

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_category_and_price, reverse_code=reset_category_and_price),
    ]
