# Generated by Django 5.2.7 on 2025-10-17 17:53

from django.db import migrations

def set_price(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")

    for item in ItemModel.objects.all():
        if item.price <=10:
            item.rarity = 'Rare'
        elif 11 <= item .price <= 20:
            item.rarity = 'Very Rare'
        elif 21 <= item.price <= 30:
            item.rarity = 'Extremely Rare'
        else:
            item.rarity = 'Mega Rare'
        item.save()

def reset_rarelty(apps, schema_editor):
    ItemModel = apps.get_model("main_app", "Item")
    defaultRarity = ItemModel._meta.get_field('rarity').default

    for item in ItemModel.objects.all():
       item.rarity = defaultRarity
       item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_migrate_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price, reverse_code=reset_rarelty),
    ]
