# Generated by Django 5.2.7 on 2025-10-17 17:57

from django.db import migrations


def update_delivery(apps, schema_editor):
    OrderModel = apps.get_model('main_app', 'Order')

    for order in OrderModel.objects.all():
        if order.status == OrderStatusChoices.PENDING:
            order.delivery = order.order_date + timedelta(days=3)
            order.save()
        elif order.status == OrderStatusChoices.COMPLETED:
            order.warranty =  "24 months"
            order.save()
        elif order.status == OrderStatusChoices.CANCELED:
            order.delete()

def reverse_migration(apps, schema_editor):
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0013_migrate_items'),
    ]

    operations = [
        migrations.RunPython(code = update_delivery,reverse_code=reverse_migration),
    ]

