# Generated by Django 5.2.7 on 2025-10-17 17:58

from django.db import migrations

def set_age_group(apps, schema_editor):
    PersonModel = apps.get_model("main_app", "Person")
    #TODO f object
    people = PersonModel.objects.all()
    for person in people:
        if person.age <=12:
            person.age_group = 'Child'
        elif person.age <= 17:
            person.age_group = 'Teen'
        else:
            person.age_group = 'Adult'

        person.save() #bad practise cuz we are making too much queries to the DB

def set_age_group_default(apps, schema_editor):
    PersonModel = apps.get_model("main_app", "Person")
    default_age_group = PersonModel._meta.get_field('age_group').default
    #todo make it update at once, use bulk update
    people = PersonModel.objects.all()
    for person in people:
        person.age_group = default_age_group
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0014_migrate_orders'),
    ]

    operations = [
        migrations.RunPython(set_age_group, reverse_code=set_age_group_default),
    ]
