# Generated by Django 5.2.7 on 2025-10-31 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_employee_veterinary_zookeeper'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Veterinary',
            new_name='Veterinarian',
        ),
    ]
