# Generated by Django 5.2.7 on 2025-10-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_veterinary_veterinarian'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZooDisplayAnimal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main_app.animal',),
        ),
        migrations.RenameField(
            model_name='zookeeper',
            old_name='speciality',
            new_name='specialty',
        ),
    ]
