# Generated by Django 5.2.7 on 2025-10-17 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=20)),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
