# Generated by Django 5.2.7 on 2025-11-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_match_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date_played',
            field=models.DateTimeField(),
        ),
    ]
