# Generated by Django 5.2.7 on 2025-10-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_book_exercise_product_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fi', 'Fiction'), ('no', 'Non-Fiction'), ('sc', 'Science Fiction'), ('h', 'Horror')], max_length=20),
        ),
    ]
